name: deploy-submit-image-prod
on:
  push:
    branches: 
      - mainline
      
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  schedule:
    - cron:  '3 10,18,23 * * 1-4'
    
jobs:
  deploy-us-west-2:
    runs-on: ubuntu-latest
    environment: prod-us-west
    
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
    # Delay the execution - deployment tracking/gating requirement
      - name: Sleep for 60 seconds
        run: sleep 60s
      - name: Deploy us-west-2
        run: echo "Deploy us-west-2"
