name: deploy-submit-image-test-staging
on:
  pull_request:
    branches:
      - mainline
  push:
    branches:
      - '**'
      - '!mainline'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: echo "Run unit tests"

  deploy-us-west-1:
    runs-on: ubuntu-latest
    environment: stg-us-west
    needs: run-unit-tests
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - name: Deploy us-west-1
        run: echo "Deploy us-west-1"

  integration-test-us-west-1:
    runs-on: ubuntu-latest
    needs: deploy-us-west-1
    steps:
      - name: Integration test us-west-1
        run: echo "Integration test us-west-1"
